### ISSUE TITLE
Please add to RomManager master manifest

### ISSUE THREAD

**Issue by maxdamage2122** [koush/ROMManagerManifest#301]
Developer JavaScript file:
https://dl.dropbox.com/s/7yreog0xtyebutn/smb_a1002-nightlies/developer.js

For an unknown reason there are no cyanogenmod nightlies for the Viewsonic GTablet. I setup a buildbot to build them for the users on xda. They have also been interested in me putting the in RomManager for easy OTA updates so I'm trying to set that up for them. 

My username over on xda is maxdamage2122 if you would like some background information on me.

Thanks in advance,
Justin

**Comment by koush** [comment]
Please use http://romshare.deployfu.com 

It also supports manual manifests.
Thanks!

**Comment by maxdamage2122** [comment]
I read about your romshare site but from my understanding you can't use "addons" or the ota update feature. Did I misunderstand it?

**Comment by koush** [comment]
You can still use manual manifests, which will let you do what you are doing now and have addons.

Basically, ROM Share is the new developer manifest submission portal. I don't add anyone through this github repository anymore.

**Comment by maxdamage2122** [comment]
Ill check it. Thanks for the help!

**Comment by maxdamage2122** [comment]
So I checked the "Manual Manifest URL (Advanced Developers Only!)" option and put in my manifest URL https://dl.dropbox.com/s/7yreog0xtyebutn/smb_a1002-nightlies/manifest.js but nothing has shown up in Rom Manager. My manifest is JSON compliant and looks right to me. Do you have any insight for what might be wrong?

**Comment by maxdamage2122** [comment]
I think I might have found the issue. For my device, the Viewsonic GTablet, cyanogenmod has renamed it from harmony to smb_a1002. Now I believe clockworkmod recovery is reporting the device as harmony and therefore RomManager is not showing any roms for smb-a1002. I came to this conclusion because in the master manifest, cyanogenmod has a RC1 for the smb_a1002 and even that is not showing up in RomManager.

**Comment by koush** [comment]
Gotcha. Let me trigger a recovery build. That'll address the rename issue.

**Comment by koush** [comment]
Check now. There should be a new gtablet listing.

**Comment by maxdamage2122** [comment]
While running a smb_a1002 rom the only recovery options are Advent Vega, Elocity A7, T-Mobile G2X, and LG Optimus 2X.

Running the last harmony rom the recovery options are Viewsonic GTab and Viewsonic GTablet (smb_a1002). On both the harmony rom and smb_a1002 rom with the new smb_a1002 recovery selecting download rom says "Error occurred while downloading the Developer list."

**Comment by koush** [comment]
I believe I just fixed the the error downloading problem. Let me know.

**Comment by maxdamage2122** [comment]
In the smb_a1002 rom CM7 RC1 and my roms now show up but with harmony roms the error still shows.

Will you also look into getting the new smb_a1002 recovery to show up in Rom Manager on smb_a1002 roms?

Thanks for all your help so far btw.
